/* 
 * Yagna Activity API
 *
 *  The Activity API can be perceived as controls which a Requestor-side application has to steer the execution of an Activity as specified in an Agreement which has been negotiated via the Market API/Protocol. This defines possible interactions between the Requestor application (via Activity API) and the generic components running on the Provider node, which host the Provider-side application code. The possible interactions imply a logical “execution environment” component, which is the host/container for the “payload” code. The “execution environment” is specified as an ExeUnit, with a generic interface via which a Provider node’s Activity Controller can operate the hosted code. It conforms with capability level 1 of the [Activity API specification] (https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM). 
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Golem.ActivityApi.Client.Api;
using Golem.ActivityApi.Client.Model;
using Golem.ActivityApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Golem.ActivityApi.Client.Test
{
    /// <summary>
    ///  Class for testing ProviderEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProviderEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProviderEvent
        //private ProviderEvent instance;

        public ProviderEventTests()
        {
            // TODO uncomment below to create an instance of ProviderEvent
            //instance = new ProviderEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProviderEvent
        /// </summary>
        [Fact]
        public void ProviderEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProviderEvent
            //Assert.IsInstanceOfType<ProviderEvent> (instance, "variable 'instance' is a ProviderEvent");
        }

        /// <summary>
        /// Test deserialize a GetActivityState from type ProviderEvent
        /// </summary>
        [Fact]
        public void GetActivityStateDeserializeFromProviderEventTest()
        {
            // TODO uncomment below to test deserialize a GetActivityState from type ProviderEvent
            //Assert.IsInstanceOf<ProviderEvent>(JsonConvert.DeserializeObject<ProviderEvent>(new GetActivityState().ToJson()));
        }
        /// <summary>
        /// Test deserialize a CreateActivity from type ProviderEvent
        /// </summary>
        [Fact]
        public void CreateActivityDeserializeFromProviderEventTest()
        {
            // TODO uncomment below to test deserialize a CreateActivity from type ProviderEvent
            //Assert.IsInstanceOf<ProviderEvent>(JsonConvert.DeserializeObject<ProviderEvent>(new CreateActivity().ToJson()));
        }
        /// <summary>
        /// Test deserialize a DestroyActivity from type ProviderEvent
        /// </summary>
        [Fact]
        public void DestroyActivityDeserializeFromProviderEventTest()
        {
            // TODO uncomment below to test deserialize a DestroyActivity from type ProviderEvent
            //Assert.IsInstanceOf<ProviderEvent>(JsonConvert.DeserializeObject<ProviderEvent>(new DestroyActivity().ToJson()));
        }
        /// <summary>
        /// Test deserialize a GetActivityUsage from type ProviderEvent
        /// </summary>
        [Fact]
        public void GetActivityUsageDeserializeFromProviderEventTest()
        {
            // TODO uncomment below to test deserialize a GetActivityUsage from type ProviderEvent
            //Assert.IsInstanceOf<ProviderEvent>(JsonConvert.DeserializeObject<ProviderEvent>(new GetActivityUsage().ToJson()));
        }

        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }
        /// <summary>
        /// Test the property 'EventDate'
        /// </summary>
        [Fact]
        public void EventDateTest()
        {
            // TODO unit test for the property 'EventDate'
        }
        /// <summary>
        /// Test the property 'ActivityId'
        /// </summary>
        [Fact]
        public void ActivityIdTest()
        {
            // TODO unit test for the property 'ActivityId'
        }
        /// <summary>
        /// Test the property 'AgreementId'
        /// </summary>
        [Fact]
        public void AgreementIdTest()
        {
            // TODO unit test for the property 'AgreementId'
        }

    }

}
