/*
 * Yagna Activity API
 *
 *  The Activity API can be perceived as controls which a Requestor-side application has to steer the execution of an Activity as specified in an Agreement which has been negotiated via the Market API/Protocol. This defines possible interactions between the Requestor application (via Activity API) and the generic components running on the Provider node, which host the Provider-side application code. The possible interactions imply a logical “execution environment” component, which is the host/container for the “payload” code. The “execution environment” is specified as an ExeUnit, with a generic interface via which a Provider node’s Activity Controller can operate the hosted code. It conforms with capability level 1 of the [Activity API specification] (https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM). 
 *
 * The version of the OpenAPI document: 1.6.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Golem.Common.Client.Client.OpenAPIDateConverter;

namespace Golem.ActivityApi.Client.Model
{
    /// <summary>
    /// CapturePart
    /// </summary>
    [DataContract(Name = "CapturePart")]
    public partial class CapturePart : IEquatable<CapturePart>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CapturePart" /> class.
        /// </summary>
        /// <param name="head">head.</param>
        /// <param name="tail">tail.</param>
        /// <param name="headtail">headtail.</param>
        public CapturePart(decimal head = default(decimal), decimal tail = default(decimal), decimal headtail = default(decimal))
        {
            this.Head = head;
            this.Tail = tail;
            this.Headtail = headtail;
        }

        /// <summary>
        /// Gets or Sets Head
        /// </summary>
        [DataMember(Name = "head", EmitDefaultValue = false)]
        public decimal Head { get; set; }

        /// <summary>
        /// Gets or Sets Tail
        /// </summary>
        [DataMember(Name = "tail", EmitDefaultValue = false)]
        public decimal Tail { get; set; }

        /// <summary>
        /// Gets or Sets Headtail
        /// </summary>
        [DataMember(Name = "headtail", EmitDefaultValue = false)]
        public decimal Headtail { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CapturePart {\n");
            sb.Append("  Head: ").Append(Head).Append("\n");
            sb.Append("  Tail: ").Append(Tail).Append("\n");
            sb.Append("  Headtail: ").Append(Headtail).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CapturePart);
        }

        /// <summary>
        /// Returns true if CapturePart instances are equal
        /// </summary>
        /// <param name="input">Instance of CapturePart to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CapturePart input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Head == input.Head ||
                    this.Head.Equals(input.Head)
                ) && 
                (
                    this.Tail == input.Tail ||
                    this.Tail.Equals(input.Tail)
                ) && 
                (
                    this.Headtail == input.Headtail ||
                    this.Headtail.Equals(input.Headtail)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Head.GetHashCode();
                hashCode = hashCode * 59 + this.Tail.GetHashCode();
                hashCode = hashCode * 59 + this.Headtail.GetHashCode();
                return hashCode;
            }
        }

    }

}
