/* 
 * Yagna Activity API
 *
 *  The Activity API can be perceived as controls which a Requestor-side application has to steer the execution of an Activity as specified in an Agreement which has been negotiated via the Market API/Protocol. This defines possible interactions between the Requestor application (via Activity API) and the generic components running on the Provider node, which host the Provider-side application code. The possible interactions imply a logical “execution environment” component, which is the host/container for the “payload” code. The “execution environment” is specified as an ExeUnit, with a generic interface via which a Provider node’s Activity Controller can operate the hosted code. It conforms with capability level 1 of the [Activity API specification] (https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM). 
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Golem.Common.Client.Client.OpenAPIDateConverter;

namespace Golem.ActivityApi.Client.Model
{
    /// <summary>
    /// CommandOutputBinAllOf
    /// </summary>
    [DataContract]
    public partial class CommandOutputBinAllOf :  IEquatable<CommandOutputBinAllOf>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommandOutputBinAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CommandOutputBinAllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CommandOutputBinAllOf" /> class.
        /// </summary>
        /// <param name="bin">bin (required).</param>
        public CommandOutputBinAllOf(List<System.IO.Stream> bin = default(List<System.IO.Stream>))
        {
            // to ensure "bin" is required (not null)
            this.Bin = bin ?? throw new ArgumentNullException("bin is a required property for CommandOutputBinAllOf and cannot be null");;
        }
        
        /// <summary>
        /// Gets or Sets Bin
        /// </summary>
        [DataMember(Name="bin", EmitDefaultValue=false)]
        public List<System.IO.Stream> Bin { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CommandOutputBinAllOf {\n");
            sb.Append("  Bin: ").Append(Bin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CommandOutputBinAllOf);
        }

        /// <summary>
        /// Returns true if CommandOutputBinAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of CommandOutputBinAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CommandOutputBinAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Bin == input.Bin ||
                    this.Bin != null &&
                    input.Bin != null &&
                    this.Bin.SequenceEqual(input.Bin)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Bin != null)
                    hashCode = hashCode * 59 + this.Bin.GetHashCode();
                return hashCode;
            }
        }

    }

}
