/* 
 * Yagna Activity API
 *
 *  The Activity API can be perceived as controls which a Requestor-side application has to steer the execution of an Activity as specified in an Agreement which has been negotiated via the Market API/Protocol. This defines possible interactions between the Requestor application (via Activity API) and the generic components running on the Provider node, which host the Provider-side application code. The possible interactions imply a logical “execution environment” component, which is the host/container for the “payload” code. The “execution environment” is specified as an ExeUnit, with a generic interface via which a Provider node’s Activity Controller can operate the hosted code. It conforms with capability level 1 of the [Activity API specification] (https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM). 
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Golem.Common.Client.Client.OpenAPIDateConverter;

namespace Golem.ActivityApi.Client.Model
{
    /// <summary>
    /// CommandOutputStrAllOf
    /// </summary>
    [DataContract]
    public partial class CommandOutputStrAllOf :  IEquatable<CommandOutputStrAllOf>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommandOutputStrAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CommandOutputStrAllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CommandOutputStrAllOf" /> class.
        /// </summary>
        /// <param name="str">str (required).</param>
        public CommandOutputStrAllOf(string str = default(string))
        {
            // to ensure "str" is required (not null)
            this.Str = str ?? throw new ArgumentNullException("str is a required property for CommandOutputStrAllOf and cannot be null");;
        }
        
        /// <summary>
        /// Gets or Sets Str
        /// </summary>
        [DataMember(Name="str", EmitDefaultValue=false)]
        public string Str { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CommandOutputStrAllOf {\n");
            sb.Append("  Str: ").Append(Str).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CommandOutputStrAllOf);
        }

        /// <summary>
        /// Returns true if CommandOutputStrAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of CommandOutputStrAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CommandOutputStrAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Str == input.Str ||
                    (this.Str != null &&
                    this.Str.Equals(input.Str))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Str != null)
                    hashCode = hashCode * 59 + this.Str.GetHashCode();
                return hashCode;
            }
        }

    }

}
