/* 
 * Yagna Activity API
 *
 *  The Activity API can be perceived as controls which a Requestor-side application has to steer the execution of an Activity as specified in an Agreement which has been negotiated via the Market API/Protocol. This defines possible interactions between the Requestor application (via Activity API) and the generic components running on the Provider node, which host the Provider-side application code. The possible interactions imply a logical “execution environment” component, which is the host/container for the “payload” code. The “execution environment” is specified as an ExeUnit, with a generic interface via which a Provider node’s Activity Controller can operate the hosted code. It conforms with capability level 1 of the [Activity API specification] (https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM). 
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using OpenAPIDateConverter = Golem.Common.Client.Client.OpenAPIDateConverter;

namespace Golem.ActivityApi.Client.Model
{
    /// <summary>
    /// ProviderEvent
    /// </summary>
    [DataContract]
    [JsonConverter(typeof(JsonSubtypes), "EventType")]
    [JsonSubtypes.KnownSubType(typeof(GetActivityState), "GetActivityState")]
    [JsonSubtypes.KnownSubType(typeof(CreateActivity), "CreateActivity")]
    [JsonSubtypes.KnownSubType(typeof(DestroyActivity), "DestroyActivity")]
    [JsonSubtypes.KnownSubType(typeof(GetActivityUsage), "GetActivityUsage")]
    [JsonSubtypes.KnownSubType(typeof(CreateActivity), "CreateActivity")]
    [JsonSubtypes.KnownSubType(typeof(DestroyActivity), "DestroyActivity")]
    [JsonSubtypes.KnownSubType(typeof(GetActivityState), "GetActivityState")]
    [JsonSubtypes.KnownSubType(typeof(GetActivityUsage), "GetActivityUsage")]
    public partial class ProviderEvent :  IEquatable<ProviderEvent>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProviderEvent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProviderEvent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProviderEvent" /> class.
        /// </summary>
        /// <param name="eventType">eventType (required).</param>
        /// <param name="eventDate">eventDate (required).</param>
        /// <param name="activityId">activityId (required).</param>
        /// <param name="agreementId">agreementId (required).</param>
        public ProviderEvent(string eventType = default(string), DateTime eventDate = default(DateTime), string activityId = default(string), string agreementId = default(string))
        {
            // to ensure "eventType" is required (not null)
            this.EventType = eventType ?? throw new ArgumentNullException("eventType is a required property for ProviderEvent and cannot be null");;
            this.EventDate = eventDate;
            // to ensure "activityId" is required (not null)
            this.ActivityId = activityId ?? throw new ArgumentNullException("activityId is a required property for ProviderEvent and cannot be null");;
            // to ensure "agreementId" is required (not null)
            this.AgreementId = agreementId ?? throw new ArgumentNullException("agreementId is a required property for ProviderEvent and cannot be null");;
        }
        
        /// <summary>
        /// Gets or Sets EventType
        /// </summary>
        [DataMember(Name="eventType", EmitDefaultValue=false)]
        public string EventType { get; set; }

        /// <summary>
        /// Gets or Sets EventDate
        /// </summary>
        [DataMember(Name="eventDate", EmitDefaultValue=false)]
        public DateTime EventDate { get; set; }

        /// <summary>
        /// Gets or Sets ActivityId
        /// </summary>
        [DataMember(Name="activityId", EmitDefaultValue=false)]
        public string ActivityId { get; set; }

        /// <summary>
        /// Gets or Sets AgreementId
        /// </summary>
        [DataMember(Name="agreementId", EmitDefaultValue=false)]
        public string AgreementId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProviderEvent {\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  EventDate: ").Append(EventDate).Append("\n");
            sb.Append("  ActivityId: ").Append(ActivityId).Append("\n");
            sb.Append("  AgreementId: ").Append(AgreementId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProviderEvent);
        }

        /// <summary>
        /// Returns true if ProviderEvent instances are equal
        /// </summary>
        /// <param name="input">Instance of ProviderEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProviderEvent input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EventType == input.EventType ||
                    (this.EventType != null &&
                    this.EventType.Equals(input.EventType))
                ) && 
                (
                    this.EventDate == input.EventDate ||
                    (this.EventDate != null &&
                    this.EventDate.Equals(input.EventDate))
                ) && 
                (
                    this.ActivityId == input.ActivityId ||
                    (this.ActivityId != null &&
                    this.ActivityId.Equals(input.ActivityId))
                ) && 
                (
                    this.AgreementId == input.AgreementId ||
                    (this.AgreementId != null &&
                    this.AgreementId.Equals(input.AgreementId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EventType != null)
                    hashCode = hashCode * 59 + this.EventType.GetHashCode();
                if (this.EventDate != null)
                    hashCode = hashCode * 59 + this.EventDate.GetHashCode();
                if (this.ActivityId != null)
                    hashCode = hashCode * 59 + this.ActivityId.GetHashCode();
                if (this.AgreementId != null)
                    hashCode = hashCode * 59 + this.AgreementId.GetHashCode();
                return hashCode;
            }
        }

    }

}
