/* 
 * Yagna Activity API
 *
 *  The Activity API can be perceived as controls which a Requestor-side application has to steer the execution of an Activity as specified in an Agreement which has been negotiated via the Market API/Protocol. This defines possible interactions between the Requestor application (via Activity API) and the generic components running on the Provider node, which host the Provider-side application code. The possible interactions imply a logical “execution environment” component, which is the host/container for the “payload” code. The “execution environment” is specified as an ExeUnit, with a generic interface via which a Provider node’s Activity Controller can operate the hosted code. It conforms with capability level 1 of the [Activity API specification] (https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM). 
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Golem.ActivityApi.Client.Client.OpenAPIDateConverter;

namespace Golem.ActivityApi.Client.Model
{
    /// <summary>
    /// RuntimeEventKindFinishedAllOf
    /// </summary>
    [DataContract]
    public partial class RuntimeEventKindFinishedAllOf :  IEquatable<RuntimeEventKindFinishedAllOf>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RuntimeEventKindFinishedAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RuntimeEventKindFinishedAllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RuntimeEventKindFinishedAllOf" /> class.
        /// </summary>
        /// <param name="finished">finished (required).</param>
        public RuntimeEventKindFinishedAllOf(RuntimeEventKindFinishedBody finished = default(RuntimeEventKindFinishedBody))
        {
            // to ensure "finished" is required (not null)
            this.Finished = finished ?? throw new ArgumentNullException("finished is a required property for RuntimeEventKindFinishedAllOf and cannot be null");;
        }
        
        /// <summary>
        /// Gets or Sets Finished
        /// </summary>
        [DataMember(Name="finished", EmitDefaultValue=false)]
        public RuntimeEventKindFinishedBody Finished { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RuntimeEventKindFinishedAllOf {\n");
            sb.Append("  Finished: ").Append(Finished).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RuntimeEventKindFinishedAllOf);
        }

        /// <summary>
        /// Returns true if RuntimeEventKindFinishedAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of RuntimeEventKindFinishedAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RuntimeEventKindFinishedAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Finished == input.Finished ||
                    (this.Finished != null &&
                    this.Finished.Equals(input.Finished))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Finished != null)
                    hashCode = hashCode * 59 + this.Finished.GetHashCode();
                return hashCode;
            }
        }

    }

}
