/* 
 * Yagna Activity API
 *
 *  The Activity API can be perceived as controls which a Requestor-side application has to steer the execution of an Activity as specified in an Agreement which has been negotiated via the Market API/Protocol. This defines possible interactions between the Requestor application (via Activity API) and the generic components running on the Provider node, which host the Provider-side application code. The possible interactions imply a logical “execution environment” component, which is the host/container for the “payload” code. The “execution environment” is specified as an ExeUnit, with a generic interface via which a Provider node’s Activity Controller can operate the hosted code. It conforms with capability level 1 of the [Activity API specification] (https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM). 
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Golem.Common.Client.Client.OpenAPIDateConverter;

namespace Golem.ActivityApi.Client.Model
{
    /// <summary>
    /// RuntimeEventKindStarted
    /// </summary>
    [DataContract]
    public partial class RuntimeEventKindStarted : RuntimeEventKind,  IEquatable<RuntimeEventKindStarted>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RuntimeEventKindStarted" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RuntimeEventKindStarted() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RuntimeEventKindStarted" /> class.
        /// </summary>
        /// <param name="started"> The specification of ExeScript commands format as per Activity API specification. Including TRANSFER command syntax extension described in [this specification](https://github.com/golemfactory/golem-architecture/blob/master/GIPS/GIP-PR0001-multifile-transfer.md). ## Implementation Notes The schemas have been defined to accept a following format of JSON command collections: &#x60;&#x60;&#x60; [ { \&quot;deploy\&quot;: {} }, { \&quot;start\&quot;: { \&quot;args\&quot;: [] } }, { \&quot;transfer\&quot;: { \&quot;from\&quot;: \&quot;http://34.244.4.185:8000/LICENSE\&quot;, \&quot;to\&quot;: \&quot;container:/input/file_in\&quot;, \&quot;format\&quot;: \&quot;zip\&quot;, \&quot;depth\&quot;: 2, \&quot;fileset\&quot;: [{\&quot;desc\&quot;:\&quot;all images\&quot;, \&quot;includes\&quot;: [\&quot;*.jpg\&quot;], \&quot;excludes\&quot;: [\&quot;db*.*\&quot;] }] } }, { \&quot;run\&quot;: { \&quot;entry_point\&quot;: \&quot;rust-wasi-tutorial\&quot;, \&quot;args\&quot;: [\&quot;/input/file_in\&quot;, \&quot;/output/file_cp\&quot;] } }, { \&quot;sign\&quot;: {} }, { \&quot;terminate\&quot;: {} }, ... ] &#x60;&#x60;&#x60; ### Rust For Rust - this format is a default representation of Rust enum types, as serialized by &#x60;serde&#x60; library. Therefore it is recommended to use this yaml specification to manually specify Rust enum types rather than depend on automatically-generated code.  (required).</param>
        public RuntimeEventKindStarted(Object started = default(Object)) : base()
        {
            // to ensure "started" is required (not null)
            this.Started = started ?? throw new ArgumentNullException("started is a required property for RuntimeEventKindStarted and cannot be null");;
        }
        
        /// <summary>
        ///  The specification of ExeScript commands format as per Activity API specification. Including TRANSFER command syntax extension described in [this specification](https://github.com/golemfactory/golem-architecture/blob/master/GIPS/GIP-PR0001-multifile-transfer.md). ## Implementation Notes The schemas have been defined to accept a following format of JSON command collections: &#x60;&#x60;&#x60; [ { \&quot;deploy\&quot;: {} }, { \&quot;start\&quot;: { \&quot;args\&quot;: [] } }, { \&quot;transfer\&quot;: { \&quot;from\&quot;: \&quot;http://34.244.4.185:8000/LICENSE\&quot;, \&quot;to\&quot;: \&quot;container:/input/file_in\&quot;, \&quot;format\&quot;: \&quot;zip\&quot;, \&quot;depth\&quot;: 2, \&quot;fileset\&quot;: [{\&quot;desc\&quot;:\&quot;all images\&quot;, \&quot;includes\&quot;: [\&quot;*.jpg\&quot;], \&quot;excludes\&quot;: [\&quot;db*.*\&quot;] }] } }, { \&quot;run\&quot;: { \&quot;entry_point\&quot;: \&quot;rust-wasi-tutorial\&quot;, \&quot;args\&quot;: [\&quot;/input/file_in\&quot;, \&quot;/output/file_cp\&quot;] } }, { \&quot;sign\&quot;: {} }, { \&quot;terminate\&quot;: {} }, ... ] &#x60;&#x60;&#x60; ### Rust For Rust - this format is a default representation of Rust enum types, as serialized by &#x60;serde&#x60; library. Therefore it is recommended to use this yaml specification to manually specify Rust enum types rather than depend on automatically-generated code. 
        /// </summary>
        /// <value> The specification of ExeScript commands format as per Activity API specification. Including TRANSFER command syntax extension described in [this specification](https://github.com/golemfactory/golem-architecture/blob/master/GIPS/GIP-PR0001-multifile-transfer.md). ## Implementation Notes The schemas have been defined to accept a following format of JSON command collections: &#x60;&#x60;&#x60; [ { \&quot;deploy\&quot;: {} }, { \&quot;start\&quot;: { \&quot;args\&quot;: [] } }, { \&quot;transfer\&quot;: { \&quot;from\&quot;: \&quot;http://34.244.4.185:8000/LICENSE\&quot;, \&quot;to\&quot;: \&quot;container:/input/file_in\&quot;, \&quot;format\&quot;: \&quot;zip\&quot;, \&quot;depth\&quot;: 2, \&quot;fileset\&quot;: [{\&quot;desc\&quot;:\&quot;all images\&quot;, \&quot;includes\&quot;: [\&quot;*.jpg\&quot;], \&quot;excludes\&quot;: [\&quot;db*.*\&quot;] }] } }, { \&quot;run\&quot;: { \&quot;entry_point\&quot;: \&quot;rust-wasi-tutorial\&quot;, \&quot;args\&quot;: [\&quot;/input/file_in\&quot;, \&quot;/output/file_cp\&quot;] } }, { \&quot;sign\&quot;: {} }, { \&quot;terminate\&quot;: {} }, ... ] &#x60;&#x60;&#x60; ### Rust For Rust - this format is a default representation of Rust enum types, as serialized by &#x60;serde&#x60; library. Therefore it is recommended to use this yaml specification to manually specify Rust enum types rather than depend on automatically-generated code. </value>
        [DataMember(Name="started", EmitDefaultValue=false)]
        public Object Started { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RuntimeEventKindStarted {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Started: ").Append(Started).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RuntimeEventKindStarted);
        }

        /// <summary>
        /// Returns true if RuntimeEventKindStarted instances are equal
        /// </summary>
        /// <param name="input">Instance of RuntimeEventKindStarted to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RuntimeEventKindStarted input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Started == input.Started ||
                    (this.Started != null &&
                    this.Started.Equals(input.Started))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Started != null)
                    hashCode = hashCode * 59 + this.Started.GetHashCode();
                return hashCode;
            }
        }

    }

}
