/* 
 * Yagna Activity API
 *
 *  The Activity API can be perceived as controls which a Requestor-side application has to steer the execution of an Activity as specified in an Agreement which has been negotiated via the Market API/Protocol. This defines possible interactions between the Requestor application (via Activity API) and the generic components running on the Provider node, which host the Provider-side application code. The possible interactions imply a logical “execution environment” component, which is the host/container for the “payload” code. The “execution environment” is specified as an ExeUnit, with a generic interface via which a Provider node’s Activity Controller can operate the hosted code. It conforms with capability level 1 of the [Activity API specification] (https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM). 
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = Golem.ActivityApi.Client.Client.OpenAPIDateConverter;

namespace Golem.ActivityApi.Client.Model
{
    /// <summary>
    /// SgxCredentials
    /// </summary>
    [DataContract]
    public partial class SgxCredentials :  IEquatable<SgxCredentials>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SgxCredentials" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SgxCredentials() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SgxCredentials" /> class.
        /// </summary>
        /// <param name="enclavePubKey">enclavePubKey (required).</param>
        /// <param name="requestorPubKey">requestorPubKey (required).</param>
        /// <param name="payloadHash">payloadHash (required).</param>
        /// <param name="iasReport">iasReport (required).</param>
        /// <param name="iasSig">iasSig (required).</param>
        public SgxCredentials(string enclavePubKey = default(string), string requestorPubKey = default(string), string payloadHash = default(string), string iasReport = default(string), string iasSig = default(string))
        {
            // to ensure "enclavePubKey" is required (not null)
            this.EnclavePubKey = enclavePubKey ?? throw new ArgumentNullException("enclavePubKey is a required property for SgxCredentials and cannot be null");;
            // to ensure "requestorPubKey" is required (not null)
            this.RequestorPubKey = requestorPubKey ?? throw new ArgumentNullException("requestorPubKey is a required property for SgxCredentials and cannot be null");;
            // to ensure "payloadHash" is required (not null)
            this.PayloadHash = payloadHash ?? throw new ArgumentNullException("payloadHash is a required property for SgxCredentials and cannot be null");;
            // to ensure "iasReport" is required (not null)
            this.IasReport = iasReport ?? throw new ArgumentNullException("iasReport is a required property for SgxCredentials and cannot be null");;
            // to ensure "iasSig" is required (not null)
            this.IasSig = iasSig ?? throw new ArgumentNullException("iasSig is a required property for SgxCredentials and cannot be null");;
        }
        
        /// <summary>
        /// Gets or Sets EnclavePubKey
        /// </summary>
        [DataMember(Name="enclavePubKey", EmitDefaultValue=false)]
        public string EnclavePubKey { get; set; }

        /// <summary>
        /// Gets or Sets RequestorPubKey
        /// </summary>
        [DataMember(Name="requestorPubKey", EmitDefaultValue=false)]
        public string RequestorPubKey { get; set; }

        /// <summary>
        /// Gets or Sets PayloadHash
        /// </summary>
        [DataMember(Name="payloadHash", EmitDefaultValue=false)]
        public string PayloadHash { get; set; }

        /// <summary>
        /// Gets or Sets IasReport
        /// </summary>
        [DataMember(Name="iasReport", EmitDefaultValue=false)]
        public string IasReport { get; set; }

        /// <summary>
        /// Gets or Sets IasSig
        /// </summary>
        [DataMember(Name="iasSig", EmitDefaultValue=false)]
        public string IasSig { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SgxCredentials {\n");
            sb.Append("  EnclavePubKey: ").Append(EnclavePubKey).Append("\n");
            sb.Append("  RequestorPubKey: ").Append(RequestorPubKey).Append("\n");
            sb.Append("  PayloadHash: ").Append(PayloadHash).Append("\n");
            sb.Append("  IasReport: ").Append(IasReport).Append("\n");
            sb.Append("  IasSig: ").Append(IasSig).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SgxCredentials);
        }

        /// <summary>
        /// Returns true if SgxCredentials instances are equal
        /// </summary>
        /// <param name="input">Instance of SgxCredentials to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SgxCredentials input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EnclavePubKey == input.EnclavePubKey ||
                    (this.EnclavePubKey != null &&
                    this.EnclavePubKey.Equals(input.EnclavePubKey))
                ) && 
                (
                    this.RequestorPubKey == input.RequestorPubKey ||
                    (this.RequestorPubKey != null &&
                    this.RequestorPubKey.Equals(input.RequestorPubKey))
                ) && 
                (
                    this.PayloadHash == input.PayloadHash ||
                    (this.PayloadHash != null &&
                    this.PayloadHash.Equals(input.PayloadHash))
                ) && 
                (
                    this.IasReport == input.IasReport ||
                    (this.IasReport != null &&
                    this.IasReport.Equals(input.IasReport))
                ) && 
                (
                    this.IasSig == input.IasSig ||
                    (this.IasSig != null &&
                    this.IasSig.Equals(input.IasSig))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EnclavePubKey != null)
                    hashCode = hashCode * 59 + this.EnclavePubKey.GetHashCode();
                if (this.RequestorPubKey != null)
                    hashCode = hashCode * 59 + this.RequestorPubKey.GetHashCode();
                if (this.PayloadHash != null)
                    hashCode = hashCode * 59 + this.PayloadHash.GetHashCode();
                if (this.IasReport != null)
                    hashCode = hashCode * 59 + this.IasReport.GetHashCode();
                if (this.IasSig != null)
                    hashCode = hashCode * 59 + this.IasSig.GetHashCode();
                return hashCode;
            }
        }

    }

}
