/* 
 * Yagna Activity API
 *
 *  The Activity API can be perceived as controls which a Requestor-side application has to steer the execution of an Activity as specified in an Agreement which has been negotiated via the Market API/Protocol. This defines possible interactions between the Requestor application (via Activity API) and the generic components running on the Provider node, which host the Provider-side application code. The possible interactions imply a logical “execution environment” component, which is the host/container for the “payload” code. The “execution environment” is specified as an ExeUnit, with a generic interface via which a Provider node’s Activity Controller can operate the hosted code. It conforms with capability level 1 of the [Activity API specification] (https://docs.google.com/document/d/1BXaN32ediXdBHljEApmznSfbuudTU8TmvOmHKl0gmQM). 
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Golem.Common.Client.Client;
using Golem.ActivityApi.Client.Model;

namespace Golem.ActivityApi.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRequestorStateApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get state of specified Activity.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>ActivityState</returns>
        ActivityState GetActivityState (string activityId);

        /// <summary>
        /// Get state of specified Activity.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>ApiResponse of ActivityState</returns>
        ApiResponse<ActivityState> GetActivityStateWithHttpInfo (string activityId);
        /// <summary>
        /// Get usage of specified Activity.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>ActivityUsage</returns>
        ActivityUsage GetActivityUsage (string activityId);

        /// <summary>
        /// Get usage of specified Activity.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>ApiResponse of ActivityUsage</returns>
        ApiResponse<ActivityUsage> GetActivityUsageWithHttpInfo (string activityId);
        /// <summary>
        /// Get running commands for a specified Activity.
        /// </summary>
        /// <remarks>
        /// **Note:** This call shall get routed directly to ExeUnit.
        /// </remarks>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>List&lt;ExeScriptCommandState&gt;</returns>
        List<ExeScriptCommandState> GetRunningCommand (string activityId);

        /// <summary>
        /// Get running commands for a specified Activity.
        /// </summary>
        /// <remarks>
        /// **Note:** This call shall get routed directly to ExeUnit.
        /// </remarks>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>ApiResponse of List&lt;ExeScriptCommandState&gt;</returns>
        ApiResponse<List<ExeScriptCommandState>> GetRunningCommandWithHttpInfo (string activityId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRequestorStateApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get state of specified Activity.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>Task of ActivityState</returns>
        System.Threading.Tasks.Task<ActivityState> GetActivityStateAsync (string activityId);

        /// <summary>
        /// Get state of specified Activity.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>Task of ApiResponse (ActivityState)</returns>
        System.Threading.Tasks.Task<ApiResponse<ActivityState>> GetActivityStateAsyncWithHttpInfo (string activityId);
        /// <summary>
        /// Get usage of specified Activity.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>Task of ActivityUsage</returns>
        System.Threading.Tasks.Task<ActivityUsage> GetActivityUsageAsync (string activityId);

        /// <summary>
        /// Get usage of specified Activity.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>Task of ApiResponse (ActivityUsage)</returns>
        System.Threading.Tasks.Task<ApiResponse<ActivityUsage>> GetActivityUsageAsyncWithHttpInfo (string activityId);
        /// <summary>
        /// Get running commands for a specified Activity.
        /// </summary>
        /// <remarks>
        /// **Note:** This call shall get routed directly to ExeUnit.
        /// </remarks>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>Task of List&lt;ExeScriptCommandState&gt;</returns>
        System.Threading.Tasks.Task<List<ExeScriptCommandState>> GetRunningCommandAsync (string activityId);

        /// <summary>
        /// Get running commands for a specified Activity.
        /// </summary>
        /// <remarks>
        /// **Note:** This call shall get routed directly to ExeUnit.
        /// </remarks>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>Task of ApiResponse (List&lt;ExeScriptCommandState&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ExeScriptCommandState>>> GetRunningCommandAsyncWithHttpInfo (string activityId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRequestorStateApi : IRequestorStateApiSync, IRequestorStateApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RequestorStateApi : IRequestorStateApi
    {
        private Golem.Common.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RequestorStateApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RequestorStateApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RequestorStateApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RequestorStateApi(String basePath)
        {
            this.Configuration = Golem.Common.Client.Client.Configuration.MergeConfigurations(
                Golem.Common.Client.Client.GlobalConfiguration.Instance,
                new Golem.Common.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Golem.Common.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Golem.Common.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Golem.Common.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RequestorStateApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RequestorStateApi(Golem.Common.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Golem.Common.Client.Client.Configuration.MergeConfigurations(
                Golem.Common.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Golem.Common.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Golem.Common.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Golem.Common.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RequestorStateApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RequestorStateApi(Golem.Common.Client.Client.ISynchronousClient client,Golem.Common.Client.Client.IAsynchronousClient asyncClient, Golem.Common.Client.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Golem.Common.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Golem.Common.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Golem.Common.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Golem.Common.Client.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Golem.Common.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get state of specified Activity. 
        /// </summary>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>ActivityState</returns>
        public ActivityState GetActivityState (string activityId)
        {
             Golem.Common.Client.Client.ApiResponse<ActivityState> localVarResponse = GetActivityStateWithHttpInfo(activityId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get state of specified Activity. 
        /// </summary>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>ApiResponse of ActivityState</returns>
        public Golem.Common.Client.Client.ApiResponse< ActivityState > GetActivityStateWithHttpInfo (string activityId)
        {
            // verify the required parameter 'activityId' is set
            if (activityId == null)
                throw new Golem.Common.Client.Client.ApiException(400, "Missing required parameter 'activityId' when calling RequestorStateApi->GetActivityState");

            Golem.Common.Client.Client.RequestOptions localVarRequestOptions = new Golem.Common.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Golem.Common.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Golem.Common.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (activityId != null)
                localVarRequestOptions.PathParameters.Add("activityId", Golem.Common.Client.Client.ClientUtils.ParameterToString(activityId)); // path parameter

            // authentication (app_key) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Golem.Common.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< ActivityState >("/activity/{activityId}/state", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetActivityState", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get state of specified Activity. 
        /// </summary>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>Task of ActivityState</returns>
        public async System.Threading.Tasks.Task<ActivityState> GetActivityStateAsync (string activityId)
        {
             Golem.Common.Client.Client.ApiResponse<ActivityState> localVarResponse = await GetActivityStateAsyncWithHttpInfo(activityId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get state of specified Activity. 
        /// </summary>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>Task of ApiResponse (ActivityState)</returns>
        public async System.Threading.Tasks.Task<Golem.Common.Client.Client.ApiResponse<ActivityState>> GetActivityStateAsyncWithHttpInfo (string activityId)
        {
            // verify the required parameter 'activityId' is set
            if (activityId == null)
                throw new Golem.Common.Client.Client.ApiException(400, "Missing required parameter 'activityId' when calling RequestorStateApi->GetActivityState");


            Golem.Common.Client.Client.RequestOptions localVarRequestOptions = new Golem.Common.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (activityId != null)
                localVarRequestOptions.PathParameters.Add("activityId", Golem.Common.Client.Client.ClientUtils.ParameterToString(activityId)); // path parameter

            // authentication (app_key) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Golem.Common.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ActivityState>("/activity/{activityId}/state", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetActivityState", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get usage of specified Activity. 
        /// </summary>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>ActivityUsage</returns>
        public ActivityUsage GetActivityUsage (string activityId)
        {
             Golem.Common.Client.Client.ApiResponse<ActivityUsage> localVarResponse = GetActivityUsageWithHttpInfo(activityId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get usage of specified Activity. 
        /// </summary>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>ApiResponse of ActivityUsage</returns>
        public Golem.Common.Client.Client.ApiResponse< ActivityUsage > GetActivityUsageWithHttpInfo (string activityId)
        {
            // verify the required parameter 'activityId' is set
            if (activityId == null)
                throw new Golem.Common.Client.Client.ApiException(400, "Missing required parameter 'activityId' when calling RequestorStateApi->GetActivityUsage");

            Golem.Common.Client.Client.RequestOptions localVarRequestOptions = new Golem.Common.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Golem.Common.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Golem.Common.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (activityId != null)
                localVarRequestOptions.PathParameters.Add("activityId", Golem.Common.Client.Client.ClientUtils.ParameterToString(activityId)); // path parameter

            // authentication (app_key) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Golem.Common.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< ActivityUsage >("/activity/{activityId}/usage", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetActivityUsage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get usage of specified Activity. 
        /// </summary>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>Task of ActivityUsage</returns>
        public async System.Threading.Tasks.Task<ActivityUsage> GetActivityUsageAsync (string activityId)
        {
             Golem.Common.Client.Client.ApiResponse<ActivityUsage> localVarResponse = await GetActivityUsageAsyncWithHttpInfo(activityId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get usage of specified Activity. 
        /// </summary>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>Task of ApiResponse (ActivityUsage)</returns>
        public async System.Threading.Tasks.Task<Golem.Common.Client.Client.ApiResponse<ActivityUsage>> GetActivityUsageAsyncWithHttpInfo (string activityId)
        {
            // verify the required parameter 'activityId' is set
            if (activityId == null)
                throw new Golem.Common.Client.Client.ApiException(400, "Missing required parameter 'activityId' when calling RequestorStateApi->GetActivityUsage");


            Golem.Common.Client.Client.RequestOptions localVarRequestOptions = new Golem.Common.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (activityId != null)
                localVarRequestOptions.PathParameters.Add("activityId", Golem.Common.Client.Client.ClientUtils.ParameterToString(activityId)); // path parameter

            // authentication (app_key) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Golem.Common.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ActivityUsage>("/activity/{activityId}/usage", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetActivityUsage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get running commands for a specified Activity. **Note:** This call shall get routed directly to ExeUnit.
        /// </summary>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>List&lt;ExeScriptCommandState&gt;</returns>
        public List<ExeScriptCommandState> GetRunningCommand (string activityId)
        {
             Golem.Common.Client.Client.ApiResponse<List<ExeScriptCommandState>> localVarResponse = GetRunningCommandWithHttpInfo(activityId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get running commands for a specified Activity. **Note:** This call shall get routed directly to ExeUnit.
        /// </summary>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>ApiResponse of List&lt;ExeScriptCommandState&gt;</returns>
        public Golem.Common.Client.Client.ApiResponse< List<ExeScriptCommandState> > GetRunningCommandWithHttpInfo (string activityId)
        {
            // verify the required parameter 'activityId' is set
            if (activityId == null)
                throw new Golem.Common.Client.Client.ApiException(400, "Missing required parameter 'activityId' when calling RequestorStateApi->GetRunningCommand");

            Golem.Common.Client.Client.RequestOptions localVarRequestOptions = new Golem.Common.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Golem.Common.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Golem.Common.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (activityId != null)
                localVarRequestOptions.PathParameters.Add("activityId", Golem.Common.Client.Client.ClientUtils.ParameterToString(activityId)); // path parameter

            // authentication (app_key) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Golem.Common.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< List<ExeScriptCommandState> >("/activity/{activityId}/command", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRunningCommand", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get running commands for a specified Activity. **Note:** This call shall get routed directly to ExeUnit.
        /// </summary>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>Task of List&lt;ExeScriptCommandState&gt;</returns>
        public async System.Threading.Tasks.Task<List<ExeScriptCommandState>> GetRunningCommandAsync (string activityId)
        {
             Golem.Common.Client.Client.ApiResponse<List<ExeScriptCommandState>> localVarResponse = await GetRunningCommandAsyncWithHttpInfo(activityId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get running commands for a specified Activity. **Note:** This call shall get routed directly to ExeUnit.
        /// </summary>
        /// <exception cref="Golem.Common.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="activityId"></param>
        /// <returns>Task of ApiResponse (List&lt;ExeScriptCommandState&gt;)</returns>
        public async System.Threading.Tasks.Task<Golem.Common.Client.Client.ApiResponse<List<ExeScriptCommandState>>> GetRunningCommandAsyncWithHttpInfo (string activityId)
        {
            // verify the required parameter 'activityId' is set
            if (activityId == null)
                throw new Golem.Common.Client.Client.ApiException(400, "Missing required parameter 'activityId' when calling RequestorStateApi->GetRunningCommand");


            Golem.Common.Client.Client.RequestOptions localVarRequestOptions = new Golem.Common.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (activityId != null)
                localVarRequestOptions.PathParameters.Add("activityId", Golem.Common.Client.Client.ClientUtils.ParameterToString(activityId)); // path parameter

            // authentication (app_key) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Golem.Common.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<ExeScriptCommandState>>("/activity/{activityId}/command", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRunningCommand", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
