/* 
 * Yagna Payment API
 *
 *  Invoicing and Payments is a fundamental area of Yagna Ecosystem functionality. It includes aspects of communication between Requestor, Provider and a selected Payment Platform, which becomes crucial when Activities are executed in the context of negotiated Agreements. Yagna applications must be able to exercise various payment models, and the Invoicing/Payment-related communication is happening in parallel to Activity control communication. To define functional patterns of Requestor/Provider interaction in this area, Payment API is specified.  An important principle of the Yagna Payment API is that the actual payment transactions are hidden behind the Invoice flow. In other words, a Yagna Application on Requestor side isn’t expected to trigger actual payment transactions. Instead it is expected to receive and accept Invoices raised by the Provider - based on Application’s Invoice Accept notifications, the Payment API implementation orchestrates the payment via a configured Payment platform.  **NOTE: This specification is work-in-progress.** 
 *
 * The version of the OpenAPI document: 1.6.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Golem.PaymentApi.Client.Api;
using Golem.PaymentApi.Client.Model;
using Golem.PaymentApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Golem.PaymentApi.Client.Test
{
    /// <summary>
    ///  Class for testing Allocation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AllocationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Allocation
        //private Allocation instance;

        public AllocationTests()
        {
            // TODO uncomment below to create an instance of Allocation
            //instance = new Allocation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Allocation
        /// </summary>
        [Fact]
        public void AllocationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Allocation
            //Assert.IsInstanceOfType<Allocation> (instance, "variable 'instance' is a Allocation");
        }


        /// <summary>
        /// Test the property 'AllocationId'
        /// </summary>
        [Fact]
        public void AllocationIdTest()
        {
            // TODO unit test for the property 'AllocationId'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'PaymentPlatform'
        /// </summary>
        [Fact]
        public void PaymentPlatformTest()
        {
            // TODO unit test for the property 'PaymentPlatform'
        }
        /// <summary>
        /// Test the property 'TotalAmount'
        /// </summary>
        [Fact]
        public void TotalAmountTest()
        {
            // TODO unit test for the property 'TotalAmount'
        }
        /// <summary>
        /// Test the property 'SpentAmount'
        /// </summary>
        [Fact]
        public void SpentAmountTest()
        {
            // TODO unit test for the property 'SpentAmount'
        }
        /// <summary>
        /// Test the property 'RemainingAmount'
        /// </summary>
        [Fact]
        public void RemainingAmountTest()
        {
            // TODO unit test for the property 'RemainingAmount'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Fact]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }
        /// <summary>
        /// Test the property 'MakeDeposit'
        /// </summary>
        [Fact]
        public void MakeDepositTest()
        {
            // TODO unit test for the property 'MakeDeposit'
        }

    }

}
